### PR TITLE
#80: when no sub folder is present, just use the target folder to save files

### PR DESCRIPTION
**Pull request by wlin98004**

### CODE REVIEW

**Comment by jadrake75** [comment]
So I am good to accept this approach.  I modified your PR to always include the current folder as <Target Folder>.  I considered disabling the control if there were no folders but I thought there have been cases (not many but I have run into it) where I need to save an image and don't have a folder yet.  So I want to put it in the root folder.

Also wrote unit tests.  We should add tests for all changes.

**Comment by wlin98004** [comment]
Thanks for the sample test code and see how you make the change on updating the folder name and path.  I did discover one issue when we use the fixed name of "<target folder>".  If we just change the parent folder with no sub folder, it does not trigger the update to the savedRegion.folder.  Here is how it can be repro.

- Save a burst image to a folder without a subfolder.
- Change the target folder to another folder without subfolder.
- Try to save the burst image again.  It will still try to save to the folder in the first step.

This may be an edge case, but I do have occasions where I want to save the burst image into 2 different folders. I can resolve this by using the full path as the savedRegion.folder.name, instead of "<Target Path>".  Not sure if that is the best solution.  I tried to find where the region.folder is updated by the folder change.

**Comment by jadrake75** [comment]
I'll look... it may be that it is not two way bound...... or detecting the change.... you gave me a use-case to verify

**Comment by jadrake75** [comment]
I believe this is ready for Merge.  Please let me know if you agree and I will merge it

**Comment by wlin98004** [comment]
Thanks for the simple solution.  I would never thought to "tickle" the array and defer the update.  More to learn.  

This PR is ready for merge.  I will let you do the honor.

**Pull request merged**
